 - name: Copy file
  # You may pin to the exact commit or the version.
  uses: canastro/copy-action@0.0.2
  with:
    # Source file
    source: D:/DevOps-Training/folder1/test.txt
    # Target file
    target: D:/DevOps-Training/folder2
